/// Country dimension, built from the union of the source region lookup and
/// every country code actually present in Orders - so no order can fall out of
/// the model for want of a dimension row.
///
/// The lookup is complete: the United States and Canada are both present and
/// both map to North America. The trap is the VALUE they map to. North
/// America's region code in this source is the literal string "NA", which
/// pandas and most CSV loaders read as a missing value; Power Query does not,
/// which is why the Excel and Tableau views were always correct while the
/// Python-exported CSVs were not.
///
/// This query renames "NA" to "NAMER" at load, so the collision cannot travel
/// downstream into DAX, visuals or exports. region_source records whether a
/// row needed that rename, which makes the size of the exposure measurable:
/// [Revenue on NA-Renamed Regions %] is 52.2% of the business.
///
/// There is no analyst patch. An earlier version of this model hand-patched
/// six country codes to NAMER to work around a defect that was really a
/// loading bug. Do not reintroduce it.
table Country
	lineageTag: 3b8daf21-5c42-43e9-8d16-9e2b7a3c4001

	column country_code
		dataType: string
		lineageTag: 3b8daf21-5c42-43e9-8d16-9e2b7a3c4002
		summarizeBy: none
		sourceColumn: country_code

		annotation SummarizationSetBy = Automatic

	/// One of NAMER, EMEA, APAC, LATAM, Unmapped.
	column region
		dataType: string
		lineageTag: 3b8daf21-5c42-43e9-8d16-9e2b7a3c4003
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	/// "source lookup (NA renamed)", "source lookup", or "unmapped". Slice any
	/// regional figure by this to see how much of it depends on reading a
	/// null-looking token correctly.
	column region_source
		dataType: string
		lineageTag: 3b8daf21-5c42-43e9-8d16-9e2b7a3c4004
		summarizeBy: none
		sourceColumn: region_source

		annotation SummarizationSetBy = Automatic

	/// TRUE for "AP" and "EU", which are not valid ISO 3166-1 alpha-2 codes and
	/// appear in neither the lookup nor any standard.
	column is_valid_iso_code
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3b8daf21-5c42-43e9-8d16-9e2b7a3c4005
		summarizeBy: none
		sourceColumn: is_valid_iso_code

		annotation SummarizationSetBy = Automatic

	partition Country = m
		mode: import
		source =
				let
				    // Columns = 3: country_code, region (raw), region_cleaned.
				    // region_cleaned is the column to use - it is where the blank
				    // values for IE and LB and the "X.x" junk for MH and PG have
				    // already been resolved. Csv.Document does not coerce "NA" to
				    // null, which is exactly why this model must not be rebuilt
				    // from a pandas export that does.
				    Source = Csv.Document(
				        File.Contents(RepoPath & "/data/region_lookup.csv"),
				        [Delimiter = ",", Columns = 3, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				    ),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    LookupNormalised = Table.AddColumn(
				        Headers,
				        "lookup_region",
				        each
				            let
				                Raw = if [region_cleaned] = null then "" else Text.Upper(Text.Trim([region_cleaned]))
				            in
				                if List.Contains({"EMEA", "APAC", "LATAM"}, Raw) then
				                    Raw
				                // "NA" is the source's code for North America and is
				                // also the default null token in pandas and most CSV
				                // loaders. Renaming to "NAMER" here makes the
				                // collision structurally impossible downstream.
				                // Do not revert.
				                else if List.Contains({"NA", "NORTH AMERICA"}, Raw) then
				                    "NAMER"
				                else
				                    null,
				        type nullable text
				    ),
				    LookupCoded = Table.AddColumn(
				        LookupNormalised,
				        "code",
				        each if [country_code] = null then "" else Text.Upper(Text.Trim([country_code])),
				        type text
				    ),
				    LookupResolved = Table.SelectRows(LookupCoded, each [lookup_region] <> null and [code] <> ""),
				    LookupMap = Record.FromList(LookupResolved[lookup_region], LookupResolved[code]),
				    // Which codes only resolve because "NA" was read as text rather
				    // than as a null. This is the model's exposure to the defect.
				    RenamedCodes = List.Buffer(
				        Table.SelectRows(
				            LookupCoded,
				            each [lookup_region] = "NAMER" and [code] <> ""
				        )[code]
				    ),
				    AllCodes = List.Sort(
				        List.Distinct(
				            List.RemoveNulls(
				                List.Combine({LookupCoded[code], Table.Column(Orders, "country_code")})
				            )
				        )
				    ),
				    CodesOnly = List.Select(AllCodes, each _ <> ""),
				    AsTable = Table.FromList(CodesOnly, Splitter.SplitByNothing(), {"country_code"}),
				    AddRegion = Table.AddColumn(
				        AsTable,
				        "region",
				        each
				            if Record.HasFields(LookupMap, [country_code]) then
				                Record.Field(LookupMap, [country_code])
				            else
				                "Unmapped",
				        type text
				    ),
				    AddSource = Table.AddColumn(
				        AddRegion,
				        "region_source",
				        each
				            if List.Contains(RenamedCodes, [country_code]) then
				                "source lookup (NA renamed)"
				            else if Record.HasFields(LookupMap, [country_code]) then
				                "source lookup"
				            else
				                "unmapped",
				        type text
				    ),
				    AddIso = Table.AddColumn(
				        AddSource,
				        "is_valid_iso_code",
				        each not List.Contains({"AP", "EU"}, [country_code]),
				        type logical
				    ),
				    Typed = Table.TransformColumnTypes(
				        AddIso,
				        {
				            {"country_code", type text},
				            {"region", type text},
				            {"region_source", type text},
				            {"is_valid_iso_code", type logical}
				        }
				    )
				in
				    Typed

	annotation PBI_ResultType = Table

